# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dealicious' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dealicious
 	pod 'Parse'
 	pod 'AlamofireImage'

end
